server:
  port: 8083

spring:
  application:
    name: notification-service

  mail:
    host: smtp.gmail.com
    port: 587
    username: *****************
    password: *****************
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true